### PR TITLE
Fix parsing dates with trailing spaces (Resolves #11)

### LINKED ISSUE #11: trailing whitespaces in date leads to null date
In some rss feeds like 
http://boerse.ard.de/index~rss.xml
are trailing whitepaces in the pubDate element

This results in a null date. Please make it more robust

### PR DESCRIPTION
**Pull request by angelosilvestre**
Fix parsing dates with trailing spaces. Resolves #11 

If a feed contains a date with trailing spaces, for example `2024-01-08T00:19:00Z `, the `updated` property of the `WebFeed` entry ends up being `null`.

This PR fixes the issue by trimming the date before parsing.

We probably want to re-organize the existing tests.

### CODE REVIEW

**Comment by angelosilvestre** [comment]
@matthew-carroll Could you please review this PR?

**Comment by matthew-carroll** [comment]
We discussed offline that we should probably just test the parser because it would be unwieldy to maintain entire XML files for a detail as specific as an extra space in a single line.

**Comment by angelosilvestre** [comment]
@matthew-carroll Updated.

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Pull request merged**
