### PR TITLE
Add podcast namespace

### PR DESCRIPTION
**Pull request by amugofjava**
Hi,

This pull request adds support for the `podcast` namespace. This is a new namespace, that is beginning to be adopted, which adds useful tags specific to podcasting such as links to transcripts, links to episode chapters and a link to a donation/funding page for example. This pull request contains the first phase of tags but there will be more to come. Please let me know what you think and if you would be happy for me to add additional tags to the `podcast` namespace as new tags are approved.

I have added additional test for the namespace which all pass.

Many thanks,

Ben.

### CODE REVIEW

**Comment by sudame** [comment]
Well, I merged null-safety PR #12 today.
Please re-open this PR from the latest master branch. 
So sorry.

**Comment by amugofjava** [comment]
No problem @sudame, I've made the changes locally. Once I have finished testing I'll push the PR again - probably tomorrow. Thanks.

**Comment by amugofjava** [comment]
Hi @sudame,

I have rebased from master and applied null-safety updates (following the same style as the other). All tests pass.

**Comment by sudame** [comment]
Thanks! I'll review this PR in a week.

**Comment by sudame** [comment]
LGTM.

**Pull request merged**
